# Syftin edge node — Windows installer (PowerShell).
# Usage:
#   powershell -ExecutionPolicy Bypass -File install-node.ps1 -Token sftn_xxx -ApiUrl https://YOUR_SITE

param(
  [string]$Token,
  [string]$ApiUrl,
  [string]$InstallDir = "$env:USERPROFILE\.syftin\node",
  [switch]$NoService,
  [switch]$Docker
)

function Install-SyftinNode {
  param(
    [Parameter(Mandatory = $true)]
    [string]$Token,
    [Parameter(Mandatory = $true)]
    [string]$ApiUrl,
    [string]$InstallDir = "$env:USERPROFILE\.syftin\node",
    [switch]$NoService,
    [switch]$Docker
  )

  $ErrorActionPreference = "Stop"
  $ApiUrl = $ApiUrl.TrimEnd("/")
  $Arch = if ([Environment]::Is64BitOperatingSystem) { "amd64" } else { "386" }

  function Write-Step($msg) { Write-Host "→ $msg" -ForegroundColor Cyan }
  function Write-Ok($msg) { Write-Host "✓ $msg" -ForegroundColor Green }
  function Write-Warn($msg) { Write-Host "! $msg" -ForegroundColor Yellow }

  function Install-DockerNode {
    if (-not (Get-Command docker -ErrorAction SilentlyContinue)) { return $false }
    Write-Step "Starting Syftin node via Docker…"
    docker rm -f syftin-node 2>$null | Out-Null
    docker run -d --name syftin-node --restart unless-stopped `
      -e "NODE_TOKEN=$Token" `
      -e "SYFTIN_API_URL=$ApiUrl" `
      syftin/node:latest | Out-Null
    Write-Ok "Docker container syftin-node is running"
    return $true
  }

  function Get-ReleaseBinary($name) {
    $urls = @(
      "$ApiUrl/releases/$name",
      "https://github.com/syftin/syftin/releases/latest/download/$name"
    )
    foreach ($url in $urls) {
      try {
        Write-Step "Downloading $name from $url…"
        Invoke-WebRequest -Uri $url -OutFile (Join-Path $InstallDir $name) -UseBasicParsing
        return $true
      } catch {
        continue
      }
    }
    return $false
  }

  function Install-NativeNode {
    New-Item -ItemType Directory -Force -Path $InstallDir | Out-Null
    $nodeExe = Join-Path $InstallDir "syftin-node.exe"
    $releaseName = "syftin-node-windows-$Arch.exe"

    if (-not (Test-Path $nodeExe)) {
      if (-not (Get-ReleaseBinary $releaseName)) {
        return $false
      }
      Move-Item -Force (Join-Path $InstallDir $releaseName) $nodeExe
      Write-Ok "Downloaded syftin-node"
    } else {
      Write-Ok "syftin-node already installed"
    }

    $pwExe = Join-Path $InstallDir "syftin-playwright.exe"
    $pwRelease = "syftin-playwright-windows-$Arch.exe"
    if (-not (Test-Path $pwExe)) {
      if (Get-ReleaseBinary $pwRelease) {
        Move-Item -Force (Join-Path $InstallDir $pwRelease) $pwExe
      }
    }
    if (Test-Path $pwExe) {
      Write-Step "Installing Chromium for JavaScript-heavy pages (one-time, ~150MB)…"
      & $pwExe install chromium
      if ($LASTEXITCODE -eq 0) { Write-Ok "Playwright Chromium ready" }
      else { Write-Warn "Playwright install failed — node will use HTTP-only fetches" }
    }

    @"
# Syftin edge node — generated by install-node.ps1
NODE_TOKEN=$Token
SYFTIN_API_URL=$ApiUrl
NODE_POLL_INTERVAL=10s
"@ | Set-Content -Path (Join-Path $InstallDir "config.env") -Encoding UTF8
    Write-Ok "Wrote config.env"

    return $true
  }

  function Register-NodeService {
    $nodeExe = Join-Path $InstallDir "syftin-node.exe"
    $launcher = Join-Path $InstallDir "start-node.cmd"
    @"
@echo off
set NODE_TOKEN=$Token
set SYFTIN_API_URL=$ApiUrl
"$nodeExe"
"@ | Set-Content -Path $launcher -Encoding ASCII

    $taskName = "SyftinNode"
    $action = New-ScheduledTaskAction -Execute $launcher -WorkingDirectory $InstallDir
    $trigger = New-ScheduledTaskTrigger -AtLogOn
    $settings = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries -RestartCount 3 -RestartInterval (New-TimeSpan -Minutes 1)
    $principal = New-ScheduledTaskPrincipal -UserId $env:USERNAME -LogonType Interactive -RunLevel Limited
    Register-ScheduledTask -TaskName $taskName -Action $action -Trigger $trigger -Settings $settings -Principal $principal -Force | Out-Null
    Start-ScheduledTask -TaskName $taskName
    Write-Ok "Background task started (Task Scheduler → $taskName)"
  }

  Write-Host ""
  Write-Host "  Syftin edge node installer (Windows)"
  Write-Host "  ────────────────────────────────────"
  Write-Host ""

  if ($Docker) {
    if (Install-DockerNode) { return }
    throw "Docker not available. Install Docker Desktop or run without -Docker."
  }

  if (-not (Install-NativeNode)) {
    Write-Warn "Native binary not found — trying Docker…"
    if (Install-DockerNode) { return }
    throw "Could not install syftin-node. See $ApiUrl/contributor/help"
  }

  if (-not $NoService) {
    Register-NodeService
  } else {
    Write-Warn "Run manually:"
    Write-Host "  `$env:NODE_TOKEN='$Token'; `$env:SYFTIN_API_URL='$ApiUrl'; & '$InstallDir\syftin-node.exe'"
  }

  Write-Host ""
  Write-Ok "Done! Open $ApiUrl/contributor/nodes — your device should show online soon."
  Write-Host "   Help: $ApiUrl/contributor/help"
  Write-Host ""
}

if ($Token -and $ApiUrl) {
  Install-SyftinNode @PSBoundParameters
}
